language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction --dev
  - composer dump-autoload -o

script: phpunit ./tests